ARG UBUNTU_VERSION=22.04

FROM debian:11-slim
RUN apt-get update && apt-get install -y curl git unzip xz-utils libglu1-mesa libxi-dev libglu1-mesa-dev

ENV FLUTTER_HOME=/usr/local/flutter
ENV PATH=$FLUTTER_HOME/bin:$PATH

RUN git clone https://github.com/flutter/flutter.git $FLUTTER_HOME
RUN flutter --version
RUN flutter precache
RUN flutter doctor