name: Rust Test

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start Docker containers
        run: docker-compose -f docker-compose.yml up -d rust-test db-test
      - name: Build
        run: docker compose exec rust-test cargo build --verbose
      - name: Run tests
        run: docker compose exec rust-test cargo test --verbose
      - name: Stop Containers
        run: docker-compose -f docker-compose.yml down
