name: Rust Test

on:
  push:
    branches:
      - '*' # 全てのブランチにワークフローを適用
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start Docker containers
        run: docker-compose -f docker-compose.yml up -d
      - name: Build
        run: docker compose exec rust-test cargo build --verbose --manifest-path /home/runner/work/lure_link/lure_link/api/Cargo.toml
      - name: Run tests
        run: docker compose exec rust-test cargo test --verbose --manifest-path /home/runner/work/lure_link/lure_link/api/Cargo.toml
